name: Build Example Site

on: [push]

jobs:
  hugo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Hugo
        run: sudo apt-get install hugo

      - name: Run Hugo
        working-directory: exampleSite
        run: hugo --themesDir ../..
