name: Build Example Site

on: [push]

jobs:
  hugo:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Hugo
      run: sudo apt-get install hugo
    - name: Run Hugo
      run: (cd exampleSite; hugo)
